### PR TITLE
5.0.0 dependency updates

### PR DESCRIPTION
**Pull request by mdoyle023**
## Description
Amending 5.0.0: The production build uses Ivy `partial` compilation mode. This exposed several circular dependencies with form-content referencing itself. Here is an example of the compilation error:
```
The component 'TabComponent' is used in the template but importing it would create a cycle: ngx-json-schema-form/projects/jsf/src/lib/form-content/tabs/tabs.component.ts -> ngx-json-schema-form/projects/jsf/src/lib/form-content/tabs/tab/tab.component.ts -> ngx-json-schema-form/projects/jsf/src/lib/form-content/form-content.component.ts -> ngx-json-schema-form/projects/jsf/src/lib/form-content/tabs/tabs.component.ts
```
This error prevent JSF from being published. To fix the problem, `jsf-form-content` can only be used in `jsf-form-content` not its descendents. It is passed as ng-content to other components. If the child component had additional nesting, it needed to un-nested to allow the form content to be passed properly. This meant that `jsf-tabstrip` and `jsf-one-of-drop-down` had to be removed. 

## Breaking Changes
Because `jsf-tabstrip` and `jsf-one-of-drop-down` were removed, the styling for them needs to change. They have instead been converted to classes: `.jsf-tabstrip` and `.jsf-one-of-drop-down`. 

After applying the styling updates, this is how a one-of-drop-down (highlighted in green) and tabstrip (highlighted in pink) look:
image

## 3rd Party Dependency Changes
None

## Internal Tracking Number
CD-10158

## PR Checklist
_All items should be done and checked before merging._
- [x] **Title:** Provide a very brief, general summary.
- [x] **Details:** Fill out the _Description_, _Breaking Changes_, _3rd Party Dependency Changes_, and _Internal Tracking Number_ sections. If there's nothing for a given section, write "None".
- [x] **Labels:** Add one or more labels.
- [x] **Run Unit Tests:** Locally run the Karma unit tests for this project before merging this PR.
- [x] **Run Lint:** Lint the project before merging this PR.
- [x] **Changelog:** If any code change in this PR will run in production, add an entry to the "Unreleased" section of the `CHANGELOG.md` file.
- [ ] **Update the Wiki:** Update the wiki with the changes for the JSF components.

### CODE REVIEW

**Comment by sshulgan** [comment]
Did you test that field persistence still works on JSF endpoints? Specifically with oneOfs?

**Comment by mdoyle023** [comment]
> Did you test that field persistence still works on JSF endpoints? Specifically with oneOfs?

Would running the cypress test for persistence cover this or is there a manual test that I should run?

**Comment by sshulgan** [comment]
> > Did you test that field persistence still works on JSF endpoints? Specifically with oneOfs?
> 
> Would running the cypress test for persistence cover this or is there a manual test that I should run?

The cypress test for field persistence just works with AS2, but that's one we can definately run. For manual tests, I think just testing with OFTP (toggling the mode, making sure fields under it persist) and S3 (Cross-Account Access sub fields should persist) should be enough

**Comment by mdoyle023** [comment]
> > > Did you test that field persistence still works on JSF endpoints? Specifically with oneOfs?
> > 
> > 
> > Would running the cypress test for persistence cover this or is there a manual test that I should run?
> 
> The cypress test for field persistence just works with AS2, but that's one we can definately run. For manual tests, I think just testing with OFTP (toggling the mode, making sure fields under it persist) and S3 (Cross-Account Access sub fields should persist) should be enough

All AzureBlob, S3, OFTP, and AS2 are all persisting

**Review by sshulgan — APPROVED** [review]

**Pull request merged**
